import Head from "next/head";
import "./globals.css";
import { Inter } from "next/font/google";
import img from "../assets/surya.jpg";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <Head> */}
        <title>Surya K S | Full Stack Developer</title>

        <meta
          name="description"
          content="Building best quality websites and web application at best cost."
        />
        <link rel="icon" href={img.src} />
        <link rel="canonical" href="https://suryaks.vercel.app/" />

        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content={`Software Engineer | Full Stack Developer`}
        />
        <meta
          property="og:description"
          content={`Building best quality websites and web application at best cost.`}
        />
        <meta property="og:url" content={`https://suryaks.vercel.app/`} />
        <meta property="og:image" content={img.src} />
        {/* share  URL the image has display */}

        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content={`Software Engineer | Full Stack Developer`}
        />
        <meta
          name="twitter:description"
          content={`Building best quality websites and web application at best cost.`}
        />
        <meta name="twitter:url" content={`https://suryaks.vercel.app/`} />
        <meta name="twitter:image" content={img.src} />

        {/* {script && (
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify(script),
            }}
          />
        )} */}
        {/* </Head> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
